title: Staff Scheduling System Documentation
description: Comprehensive documentation for our multi-tenant staff scheduling platform
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
plugins:
  - jekyll-feed

# Site settings
author: Your Company
email: support@yourcompany.com

# Navigation
header_pages:
  - docs/login.md
  - docs/full-setup-example.md
  - docs/roles-and-permissions.md
  - docs/users.md
  - docs/user-flows.md
  - docs/locations.md
  - docs/schedule-templates.md
  - docs/tasks.md

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
