title: Staff Scheduling System Documentation
description: Comprehensive documentation for our multi-tenant staff scheduling platform
baseurl: "/company-management-docs"
url: "https://maresergiu.github.io"

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Site settings
author: Your Company
email: support@yourcompany.com

# Minimal theme specific settings
logo: # Add logo path if you have one
show_downloads: false

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
